name: 'Check package version'

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install nodejs'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: 'Extract current project version'
        id: current_version_step
        run: |
          version=$(node -p "require('./package.json').version")
          echo "current_version=$version" >> $GITHUB_OUTPUT
      - name: 'Extract last release version'
        id: last_release_version_step
        uses: joutvhu/get-release@v1
        with:
          latest: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Pack package'
        if: ${{ steps.current_version_step.current_version != steps.last_release_version_step.tag_name }} 
        run: |
          npm pack
      - name: 'Create release'
        if: ${{ steps.current_version_step.current_version != steps.last_release_version_step.tag_name }} 
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          tag_name: ${{ steps.current_version_step.current_version }}
          name: ${{ steps.current_version_step.current_version }}
          prerelease: true
          generate_release_notes: true
          files: |
            *.tgz
